language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - mvn clean install sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=ishaan-puniani_GameExecutionServer

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
