language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - mvn clean install sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=788fc4c0be6f35cde4dda4c679ad2d1d92fd32d2

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
